allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@strapi/admin@5.52.2'
  - '@strapi/cloud-cli@5.52.2'
  - '@strapi/content-manager@5.52.2'
  - '@strapi/content-releases@5.52.2'
  - '@strapi/content-type-builder@5.52.2'
  - '@strapi/core@5.52.2'
  - '@strapi/data-transfer@5.52.2'
  - '@strapi/database@5.52.2'
  - '@strapi/email@5.52.2'
  - '@strapi/generators@5.52.2'
  - '@strapi/i18n@5.52.2'
  - '@strapi/logger@5.52.2'
  - '@strapi/openapi@5.52.2'
  - '@strapi/permissions@5.52.2'
  - '@strapi/plugin-cloud@5.52.2'
  - '@strapi/plugin-users-permissions@5.52.2'
  - '@strapi/provider-email-sendmail@5.52.2'
  - '@strapi/provider-upload-local@5.52.2'
  - '@strapi/review-workflows@5.52.2'
  - '@strapi/strapi@5.52.2'
  - '@strapi/types@5.52.2'
  - '@strapi/typescript-utils@5.52.2'
  - '@strapi/upload@5.52.2'
  - '@strapi/utils@5.52.2'

onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - sharp
